version: "3.9"

services:
  client:
    build:
      context: client/
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
  json-server:
    build:
      context: json-server/
      dockerfile: Dockerfile
    ports:
      - "8081:5000"
    restart: unless-stopped